/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yumexpress.gui;

import java.awt.Image;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import yumexpress.dao.ProductDAO;
import yumexpress.pojo.ProductPojo;
import yumexpress.utility.OwnerProfile;
import yumexpress.utility.SpoonacularAPI;

/**
 *
 * @author Isha Rathore
 */
public class AddFoodFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddFoodFrame
     * 
     */
    ProductPojo product;
    private List<ProductPojo>foodList;
    private int foodIndex=0;
    public AddFoodFrame() {
        initComponents();
        setLocationRelativeTo(null);
        this.lblOwnerProfile.setText("Hello "+OwnerProfile.getOwnerName());
        clearAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblOwnerProfile = new javax.swing.JLabel();
        btnAddFood = new javax.swing.JButton();
        btnViewFood = new javax.swing.JButton();
        btnViewStaff = new javax.swing.JButton();
        btnOrderList = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnaddstaff = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSearchFood = new javax.swing.JTextField();
        txtFoodName = new javax.swing.JTextField();
        txtFoodPrice = new javax.swing.JTextField();
        lblPrev = new javax.swing.JLabel();
        lblNext = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        btnAddItem = new javax.swing.JButton();
        lblFoodImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(145, 47, 158));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yumexpress/icons/user.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 160, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 350, -1));

        lblOwnerProfile.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel2.add(lblOwnerProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 260, -1));

        btnAddFood.setBackground(new java.awt.Color(102, 255, 51));
        btnAddFood.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddFood.setText("Add Food");
        btnAddFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFoodActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 170, -1));

        btnViewFood.setBackground(new java.awt.Color(102, 255, 51));
        btnViewFood.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnViewFood.setText("View Food");
        btnViewFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewFoodActionPerformed(evt);
            }
        });
        jPanel2.add(btnViewFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 170, -1));

        btnViewStaff.setBackground(new java.awt.Color(102, 255, 51));
        btnViewStaff.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnViewStaff.setText("View Staff");
        btnViewStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStaffActionPerformed(evt);
            }
        });
        jPanel2.add(btnViewStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 170, -1));

        btnOrderList.setBackground(new java.awt.Color(102, 255, 51));
        btnOrderList.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnOrderList.setText("Order List");
        btnOrderList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderListActionPerformed(evt);
            }
        });
        jPanel2.add(btnOrderList, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 170, -1));

        btnBack.setBackground(new java.awt.Color(204, 204, 204));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, -1, -1));

        btnaddstaff.setBackground(new java.awt.Color(102, 255, 51));
        btnaddstaff.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnaddstaff.setText("Add Staff");
        btnaddstaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddstaffActionPerformed(evt);
            }
        });
        jPanel2.add(btnaddstaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 170, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 720));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(149, 14, 172));
        jLabel1.setText("Add Food Item");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 410, 90));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("Search Food");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 172, -1, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("Food Name");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setText("Food Image");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 102));
        jLabel7.setText("Enter Price");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, -1, -1));

        txtSearchFood.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel3.add(txtSearchFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 230, -1));

        txtFoodName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtFoodName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFoodNameActionPerformed(evt);
            }
        });
        jPanel3.add(txtFoodName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 230, -1));

        txtFoodPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel3.add(txtFoodPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, 220, -1));

        lblPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yumexpress/icons/icons8-left-arrow-64 (1).png"))); // NOI18N
        lblPrev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPrevMouseClicked(evt);
            }
        });
        jPanel3.add(lblPrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, -1, -1));

        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yumexpress/icons/icons8-right-arrow-64 (1).png"))); // NOI18N
        lblNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNextMouseClicked(evt);
            }
        });
        jPanel3.add(lblNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, -1, -1));

        btnSearch.setBackground(new java.awt.Color(153, 255, 102));
        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel3.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 120, -1));

        btnAddItem.setBackground(new java.awt.Color(153, 255, 102));
        btnAddItem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddItem.setText("Add Item");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });
        jPanel3.add(btnAddItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 600, 140, -1));
        jPanel3.add(lblFoodImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 230, 220));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 610, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewFoodActionPerformed
        // TODO add your handling code here:
        ViewFoodFrame f = null;
        try {
            f = new ViewFoodFrame();
        } catch (IOException ex) {
            Logger.getLogger(AddFoodFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        f.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnViewFoodActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String searchFood=this.txtSearchFood.getText().trim();
        if(searchFood.isEmpty()){
            JOptionPane.showMessageDialog(null,"Please type a food");
            return;
        }
        try{
            searchFood=searchFood.replaceAll(" ", "-");
            foodList=SpoonacularAPI.getAllItemDetailsByName(searchFood);
            if(foodList.isEmpty()){
                JOptionPane.showMessageDialog(null,"No food details for "+searchFood+" found");
                return;
            }
            foodIndex=0;
            this.lblNext.setEnabled(true);
            this.lblPrev.setEnabled(true);
            showFoodDetailsByIndex(foodIndex);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Exception while using API");
            ex.printStackTrace();
            
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void lblNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNextMouseClicked
        // TODO add your handling code here:
        foodIndex++;
        if(foodIndex>=foodList.size())
            foodIndex=0;
        showFoodDetailsByIndex(foodIndex);
        
    }//GEN-LAST:event_lblNextMouseClicked

    private void lblPrevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrevMouseClicked
        // TODO add your handling code here:
        foodIndex--;
        if(foodIndex<0)
            foodIndex=foodList.size()-1;
        showFoodDetailsByIndex(foodIndex);
    }//GEN-LAST:event_lblPrevMouseClicked

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        // TODO add your handling code here:
        if(!validateInputs()){
            JOptionPane.showMessageDialog(null,"Please fill all the data");
            return;
        }
        try{
            double price=Double.parseDouble(this.txtFoodPrice.getText().trim());
            product.setCompanyId(OwnerProfile.getCompanyId());
            product.setProductName(this.txtFoodName.getText().trim());
            product.setProductPrice(price);
            boolean res=ProductDAO.addProduct(product);
            if(!res){
                JOptionPane.showMessageDialog(null,"Cannot add the product");
                return;
            }
            JOptionPane.showMessageDialog(null,"Product Successfully added");
            foodList.remove(foodIndex);
            if(foodList.isEmpty()){
                JOptionPane.showMessageDialog(null,"All varieties of "+this.txtSearchFood.getText()+" added");
                clearAll();
                return;
            }
            foodIndex=0;
            showFoodDetailsByIndex(foodIndex);
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"DB Error");
            ex.printStackTrace();
        }
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null,"Please input numeric values for the price");
            ex.printStackTrace();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null,"Exception in DAO Image Processing");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnAddItemActionPerformed

    private void txtFoodNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFoodNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFoodNameActionPerformed

    private void btnAddFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFoodActionPerformed
        // TODO add your handling code here:
         AddFoodFrame addFood=new AddFoodFrame();
        addFood.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddFoodActionPerformed

    private void btnViewStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStaffActionPerformed
        // TODO add your handling code here:
        ViewDeliveryStaff f=new ViewDeliveryStaff();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnViewStaffActionPerformed

    private void btnOrderListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderListActionPerformed
        // TODO add your handling code here:
        OrderListFrame f=new OrderListFrame();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOrderListActionPerformed

    private void btnaddstaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddstaffActionPerformed
        // TODO add your handling code here:
        AddDeliveryStaff addStaff=new AddDeliveryStaff();
        addStaff.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnaddstaffActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        SellerOptionFrame f=new SellerOptionFrame();
        f.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFoodFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFoodFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFoodFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFoodFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFoodFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFood;
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnOrderList;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnViewFood;
    private javax.swing.JButton btnViewStaff;
    private javax.swing.JButton btnaddstaff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblFoodImage;
    private javax.swing.JLabel lblNext;
    private javax.swing.JLabel lblOwnerProfile;
    private javax.swing.JLabel lblPrev;
    private javax.swing.JTextField txtFoodName;
    private javax.swing.JTextField txtFoodPrice;
    private javax.swing.JTextField txtSearchFood;
    // End of variables declaration//GEN-END:variables
    private void showFoodDetailsByIndex(int foodIndex) {     
        
        product=foodList.get(foodIndex);
        String foodName=product.getProductName();        
        if(foodName.length()>=20){
            foodName=foodName.substring(0,20)+"...";       
        }
        txtFoodName.setText(foodName);       
        Image img=product.getProductImage();
        img=img.getScaledInstance(lblFoodImage.getWidth(),lblFoodImage.getHeight(), Image.SCALE_SMOOTH);       
        ImageIcon icon=new ImageIcon(img);
        lblFoodImage.setIcon(icon);    
    }
    private boolean validateInputs(){
        if(this.txtFoodName.getText().isEmpty()||this.txtFoodPrice.getText().isEmpty()||this.lblFoodImage.getIcon()==null){
            return false;
        }
        return true;
    }

    private void clearAll() {
       this.txtFoodName.setText("");
       this.txtSearchFood.setText("");
       this.txtFoodPrice.setText("");
       this.lblFoodImage.setIcon(null);
       this.lblNext.setEnabled(false);
       this.lblPrev.setEnabled(false);
       this.txtSearchFood.requestFocus();
    }
    
}
