/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yumexpress.gui;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import yumexpress.utility.OwnerProfile;

/**
 *
 * @author Isha Rathore
 */
public class SellerOptionFrame extends javax.swing.JFrame {

    /**
     * Creates new form SellerOptionFrame
     */
    public SellerOptionFrame() {
        initComponents();
        setLocationRelativeTo(null);
        this.lblOwnerProfile.setText("Hello "+OwnerProfile.getOwnerName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblOwnerProfile = new javax.swing.JLabel();
        btnaddfood = new javax.swing.JButton();
        btnaddstaff = new javax.swing.JButton();
        btnviewfood = new javax.swing.JButton();
        btnviewstaff = new javax.swing.JButton();
        btnorderlist = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(145, 47, 158));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yumexpress/icons/user.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 160, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 350, -1));

        lblOwnerProfile.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel2.add(lblOwnerProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 250, -1));

        btnaddfood.setBackground(new java.awt.Color(102, 255, 51));
        btnaddfood.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnaddfood.setText("Add Food");
        btnaddfood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddfoodActionPerformed(evt);
            }
        });
        jPanel2.add(btnaddfood, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 170, -1));

        btnaddstaff.setBackground(new java.awt.Color(102, 255, 51));
        btnaddstaff.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnaddstaff.setText("Add Staff");
        btnaddstaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddstaffActionPerformed(evt);
            }
        });
        jPanel2.add(btnaddstaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 170, -1));

        btnviewfood.setBackground(new java.awt.Color(102, 255, 51));
        btnviewfood.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnviewfood.setText("View Food");
        btnviewfood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewfoodActionPerformed(evt);
            }
        });
        jPanel2.add(btnviewfood, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 170, -1));

        btnviewstaff.setBackground(new java.awt.Color(102, 255, 51));
        btnviewstaff.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnviewstaff.setText("View Staff");
        btnviewstaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewstaffActionPerformed(evt);
            }
        });
        jPanel2.add(btnviewstaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 170, -1));

        btnorderlist.setBackground(new java.awt.Color(153, 255, 51));
        btnorderlist.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnorderlist.setText("Order List");
        btnorderlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnorderlistActionPerformed(evt);
            }
        });
        jPanel2.add(btnorderlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, 170, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 710));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yumexpress/icons/seller option.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 370, 330));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(134, 19, 163));
        jLabel2.setText("Seller Options");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 340, 80));

        jButton1.setBackground(new java.awt.Color(153, 255, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Logout");
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 600, 130, -1));

        jButton2.setBackground(new java.awt.Color(153, 255, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Delete Account");
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 600, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 610, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddstaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddstaffActionPerformed
        // TODO add your handling code here:
        AddDeliveryStaff addStaff=new AddDeliveryStaff();
        addStaff.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnaddstaffActionPerformed

    private void btnaddfoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddfoodActionPerformed
        // TODO add your handling code here:
        AddFoodFrame addFood=new AddFoodFrame();
        addFood.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnaddfoodActionPerformed

    private void btnviewfoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewfoodActionPerformed
        // TODO add your handling code here:
        ViewFoodFrame viewFood=null;
        try {
            viewFood = new ViewFoodFrame();
        } catch (IOException ex) {
            Logger.getLogger(SellerOptionFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
  
        viewFood.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnviewfoodActionPerformed

    private void btnviewstaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewstaffActionPerformed
        // TODO add your handling code here:
        ViewDeliveryStaff viewStaff=new ViewDeliveryStaff();
        viewStaff.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnviewstaffActionPerformed

    private void btnorderlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnorderlistActionPerformed
        // TODO add your handling code here:
        OrderListFrame orderList=new OrderListFrame();
        orderList.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnorderlistActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellerOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellerOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellerOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellerOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellerOptionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddfood;
    private javax.swing.JButton btnaddstaff;
    private javax.swing.JButton btnorderlist;
    private javax.swing.JButton btnviewfood;
    private javax.swing.JButton btnviewstaff;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblOwnerProfile;
    // End of variables declaration//GEN-END:variables
}
