/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yumexpress.gui;

import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import yumexpress.dao.StaffDAO;
import yumexpress.pojo.StaffPojo;
import yumexpress.utility.OwnerProfile;

/**
 *
 * @author Isha Rathore
 */
public class ViewDeliveryStaff extends javax.swing.JFrame {

    /**
     * Creates new form ViewDeliveryStaff
     */
    private List<String>staffList;
    public ViewDeliveryStaff() {
        initComponents();
        setLocationRelativeTo(null);
        this.txtComapanyName.setText(OwnerProfile.getCompanyName());
        loadAllStaffId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        btnAddFood = new javax.swing.JButton();
        btnViewFood = new javax.swing.JButton();
        btnViewStaff = new javax.swing.JButton();
        btnOrderList = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnaddstaff = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtstaffName = new javax.swing.JTextField();
        txtComapanyName = new javax.swing.JTextField();
        txtEmailId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jcstaffId = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(145, 47, 158));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yumexpress/icons/user.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 160, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 350, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("@null");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        btnAddFood.setBackground(new java.awt.Color(102, 255, 51));
        btnAddFood.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddFood.setText("Add Food");
        btnAddFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFoodActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 170, -1));

        btnViewFood.setBackground(new java.awt.Color(102, 255, 51));
        btnViewFood.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnViewFood.setText("View Food");
        btnViewFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewFoodActionPerformed(evt);
            }
        });
        jPanel2.add(btnViewFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 170, -1));

        btnViewStaff.setBackground(new java.awt.Color(102, 255, 51));
        btnViewStaff.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnViewStaff.setText("View Staff");
        btnViewStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStaffActionPerformed(evt);
            }
        });
        jPanel2.add(btnViewStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 170, -1));

        btnOrderList.setBackground(new java.awt.Color(102, 255, 51));
        btnOrderList.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnOrderList.setText("Order List");
        btnOrderList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderListActionPerformed(evt);
            }
        });
        jPanel2.add(btnOrderList, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 170, -1));

        btnBack.setBackground(new java.awt.Color(204, 204, 204));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, -1, -1));

        btnaddstaff.setBackground(new java.awt.Color(102, 255, 51));
        btnaddstaff.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnaddstaff.setText("Add Staff");
        btnaddstaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddstaffActionPerformed(evt);
            }
        });
        jPanel2.add(btnaddstaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 170, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 720));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(140, 84, 158));
        jLabel5.setText("Email");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(140, 84, 158));
        jLabel6.setText("Company Name");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(140, 84, 158));
        jLabel7.setText("Staff ID");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(140, 84, 158));
        jLabel8.setText("Name");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        txtstaffName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtstaffName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstaffNameActionPerformed(evt);
            }
        });
        jPanel3.add(txtstaffName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 250, -1));

        txtComapanyName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel3.add(txtComapanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 250, -1));

        txtEmailId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel3.add(txtEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 250, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(151, 45, 195));
        jLabel1.setText("View Staff");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 330, 90));

        jcstaffId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcstaffId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcstaffIdActionPerformed(evt);
            }
        });
        jPanel3.add(jcstaffId, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 250, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 640, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewFoodActionPerformed
        // TODO add your handling code here:
                ViewFoodFrame f = null;
        try {
            f = new ViewFoodFrame();
        } catch (IOException ex) {
            Logger.getLogger(AddFoodFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnViewFoodActionPerformed

    private void txtstaffNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstaffNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstaffNameActionPerformed

    private void jcstaffIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcstaffIdActionPerformed
        // TODO add your handling code here:
        String selStaffId=this.jcstaffId.getSelectedItem().toString();
        try{
            StaffPojo staff=StaffDAO.getStaffDetailsByStaffId(selStaffId);
            this.txtEmailId.setText(staff.getEmailId());
            this.txtstaffName.setText(staff.getStaffName());
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Db Error in viewStaff ");
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_jcstaffIdActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
                SellerOptionFrame f=new SellerOptionFrame();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnaddstaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddstaffActionPerformed
        // TODO add your handling code here:
        AddDeliveryStaff addStaff=new AddDeliveryStaff();
        addStaff.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnaddstaffActionPerformed

    private void btnAddFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFoodActionPerformed
        // TODO add your handling code here:
              AddFoodFrame addFood=new AddFoodFrame();
        addFood.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddFoodActionPerformed

    private void btnViewStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStaffActionPerformed
        // TODO add your handling code here:
            ViewDeliveryStaff f=new ViewDeliveryStaff();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnViewStaffActionPerformed

    private void btnOrderListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderListActionPerformed
        // TODO add your handling code here:
            OrderListFrame f=new OrderListFrame();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOrderListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewDeliveryStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewDeliveryStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewDeliveryStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewDeliveryStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewDeliveryStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFood;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnOrderList;
    private javax.swing.JButton btnViewFood;
    private javax.swing.JButton btnViewStaff;
    private javax.swing.JButton btnaddstaff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> jcstaffId;
    private javax.swing.JTextField txtComapanyName;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JTextField txtstaffName;
    // End of variables declaration//GEN-END:variables

    private void loadAllStaffId() {
        try{
            staffList=StaffDAO.getALLStaffIdByCompanyId(OwnerProfile.getCompanyId());
            if(staffList.isEmpty()){
                JOptionPane.showMessageDialog(null,"No staff Added yet");
                return;
            }
            for(String staffId:staffList){
                this.jcstaffId.addItem(staffId);
            }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"DB error in viewDeliveryStaff frame" );
            ex.printStackTrace();
        }
        
    }
}
